alias c="clear"
alias cat="bat -p"
alias ls="exa -1TF --sort=Name --git --level=1 -d --git --group-directories-first"
alias n="n -e -a -P p -G"
alias k="microk8s.kubectl"
alias du="dust"
alias zsh="export LD_PRELOAD=/usr/lib/libvulkan.so.1; /usr/bin/mpv '$@'"
alias juju="TERM=xterm-256color juju"
