export EDITOR="nvim"
export VISUAL="nvim"
export PATH="/home/marc/.pyenv/shims:${PATH}"
export LS_COLORS=$(vivid generate ~/.config/vivid/one-dark.yaml)
export PATH="$HOME/.poetry/bin:$PATH"
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000000 
export SAVEHIST=10000000 
export TERM=xterm-256color
