format = """
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$character"""

[directory]
style = "bold #C678DD"

[character]
success_symbol = "[❯](#98C379 bold)"
error_symbol = "[❯](#E06C75 bold)"
vicmd_symbol = "[❮](#E5C07B bold)"

[git_branch]
format = "[$branch]($style)"
style = "#56B6C2"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
